version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats: all

python:
   version: 3.7
   install:
      - requirements: docs/requirements.txt
      - requiremnets: requirements.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
   system_packages: true
